name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]

    steps:
    - uses: actions/checkout@v4
    - name: Clone LFS objects
      run: git lfs pull --include="models/GPT2/model.onnx" --exclude="*"
    - name: Build
      run: cargo build --release
    - name: Run tests
      run: cargo test --release
    - name: Run bindings tests (Windows)
      run: ${{ github.workspace }}/test_bindings.ps1
      shell: pwsh
      if: matrix.os == 'windows-latest'
    - name: Run bindings tests (Linux, macOS)
      run: ${{ github.workspace }}/test_bindings.sh
      shell: bash
      if: matrix.os != 'windows-latest'
    
